[reticulum]
enable_transport = yes
share_instance = Yes
shared_instance_port = 37428

[logging]
loglevel = 4

[interfaces]
{% if enable_server %}
  [[Node TCP Server]]
    type = TCPServerInterface
    enabled = yes
    mode = gateway
    listen_ip = 0.0.0.0
    listen_port = {{ rns_server_port }}
{% if enable_discovery %}
    discoverable = yes
{% endif %}

{% endif %}
{% for peer in peers %}
  [[Bootstrap {{ loop.index }}]]
    type = TCPClientInterface
    enabled = yes
    target_host = {{ peer.host }}
    target_port = {{ peer.port }}
{% endfor %}
